[tool.coverage.run]
source = ["./src/"]
command_line = "-m pytest tests/"

omit = [
    # Only has imports, nothing to test
    "src/pipeline/__init__.py",
]

[tool.coverage.report]
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    # Don't report any abstract methods
    "@abstractmethod",
    # Don't report on any ...
    "\\.\\.\\.",
    # No need to test typing modules
    "if TYPE_CHECKING:",
]

skip_covered = true
skip_empty = true
show_missing = true

[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = [
    "feature_selection"
]

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unreachable = true
show_error_codes = true
follow_imports = "silent"

[[tool.mypy.overrides]]
module = [
    "sklearn.*",
    "matplotlib.*",
    "skrebate",
    "statsmodels.stats.multitest",
    "joblib",
    "openpyxl.*",
    "docx.*",
    "scipy.stats",
    "umap.*",
    "seaborn.*",
    "pandas",
    "missingpy"
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true